runtime: nodejs12
service: hooket

network:
  session_affinity: true

automatic_scaling:
  max_instances: 3
  max_idle_instances: 1
  target_cpu_utilization: 0.8

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301